[program:taimeibot]
command=python main.py
directory=/home/liuxl/TaimeiBot-1.2
autostart=true
autorestart=true
startretries=3
stderr_logfile=/home/liuxl/TaimeiBot-1.2/logs/taimeibot.stderr.log
stdout_logfile=/home/liuxl/TaimeiBot-1.2/logs/taimeibot.stdout.log
